#!/bin/bash

# Up -- Debian/Ubuntu Update Tool (Version 1.1)
# Advanced command to fully update system: "up" Adding the option "--clean" will
# remove orphaned packages and auto-clean the apt cache. (January, 2018)
# By Joe Collins www.ezeelinux.com (GNU/General Public License version 2.0)

# Set BASH to quit script and exit on errors:

set -e

# Variable defaults
CLEAN=no

# Functions:

# update function
# => if CLEAN is set to "yes", then execute clean
# => CLEAN will be set to "yes" if --clean is specified
#    at the command line.
function update() {

    echo "Starting full system update..."
    sudo apt update
    sudo apt dist-upgrade -yy
    [ "Xyes" == "X${CLEAN}" ] && clean

}

function clean() {

    echo "Cleaning up..."
    sudo apt autoremove -yy
    sudo apt autoclean

}

function leave() {

cat << _EOF_
--------------------
- Update Complete! -
--------------------
_EOF_
exit 0

}

function up-help() {

cat << _EOF_

 Up is a tool that automates the update procedure for Debian and Ubuntu based
 Linux systems.

 Commands:
    up = full system update.

    Running "up" with no options will update the apt cache and then perform a
    full distribution update automatically.

    up --clean = full system update with cleanup.

    Adding the "--clean" option will invoke the apt commands to search for and
    remove locally cached packages that are no longer in the repositories and
    remove orphaned packages that are no longer needed by programs.

    up --help = shows this help page.

 By Joe Collins www.ezeelinux.com (GNU/General Public License version 2.0)

_EOF_

# go ahead and leave
exit 0

}

# Execution.

# Tell 'em who we are...

echo "Up -- Debian/Ubuntu Update Tool (Version 1.1)"

for arg in $*
do
    case "${arg}" in
	--clean)
	    CLEAN=yes;;
	--help)
	    up-help;;
	*)
	    echo "Up Error: Invalid argument ${arg}. Try 'up --help' for more info." >&2
	    exit 1;;
    esac
done

# if you get here, go ahead and update
update
leave
